<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Spare Parts Consumption Report</title>

    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 12px;
            color: #212529;
        }

        .header {
            border-bottom: 2px solid #0d6efd;
            padding-bottom: 10px;
            margin-bottom: 20px;
        }

        .header h2 {
            margin: 0;
        }

        .meta {
            font-size: 11px;
            color: #555;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 15px;
        }

        th,
        td {
            border: 1px solid #dee2e6;
            padding: 6px 8px;
            text-align: left;
        }

        th {
            background: #f8f9fa;
            font-weight: bold;
        }

        .badge-issue {
            color: #fff;
            background: #dc3545;
            padding: 2px 6px;
            border-radius: 4px;
            font-size: 10px;
        }

        .badge-return {
            color: #fff;
            background: #198754;
            padding: 2px 6px;
            border-radius: 4px;
            font-size: 10px;
        }

        .footer {
            margin-top: 30px;
            font-size: 10px;
            text-align: center;
            color: #777;
        }
    </style>
</head>

<body>

    {{-- HEADER --}}
    <div class="header">
        <h2>Spare Parts Consumption Report</h2>
        <div class="meta">
            Generated at: {{ now()->format('Y-m-d H:i') }} <br>
            Generated by: {{ auth()->user()->name }}
        </div>
    </div>

    {{-- TABLE --}}
    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th>Spare Part</th>
                <th>Type</th>
                <th>Qty</th>
                <th>Project</th>
                <th>By</th>
            </tr>
        </thead>
        <tbody>
            @foreach($rows as $row)
                <tr>
                    <td>{{ $row->created_at->format('Y-m-d') }}</td>
                    <td>{{ $row->sparePart->name ?? '-' }}</td>
                    <td>
                        @if($row->type === 'issue')
                            <span class="badge-issue">ISSUE</span>
                        @else
                            <span class="badge-return">RETURN</span>
                        @endif
                    </td>
                    <td>{{ $row->quantity }}</td>
                    <td>{{ $row->breakdown->project->name ?? '-' }}</td>
                    <td>{{ $row->performer->name ?? '-' }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    {{-- FOOTER --}}
    <div class="footer">
        DMSys – Medical Devices Maintenance System
    </div>

</body>

</html>